-- Generated by Oracle SQL Developer Data Modeler 24.3.1.351.0831
--   at:        2025-11-02 21:37:56 EST
--   site:      Oracle Database 21c
--   type:      Oracle Database 21c



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE JS_DIM_CUSTOMER 
    ( 
     customer_id   INTEGER  NOT NULL , 
     customer_code VARCHAR2 (20)  NOT NULL , 
     customer_name VARCHAR2 (50)  NOT NULL , 
     segment_name  VARCHAR2 (50)  NOT NULL , 
     TBL_LAST_DT   DATE  NOT NULL 
    ) 
;

ALTER TABLE JS_DIM_CUSTOMER 
    ADD CONSTRAINT JS_DIM_CUSTOMER_PK PRIMARY KEY ( customer_id ) ;

CREATE TABLE JS_DIM_DATE 
    ( 
     date_id           INTEGER  NOT NULL , 
     full_date         DATE , 
     days              VARCHAR2 (2) , 
     month_short       VARCHAR2 (3) , 
     month_num         VARCHAR2 (2) , 
     month_long        VARCHAR2 (9) , 
     day_of_week_short VARCHAR2 (1) , 
     day_of_week_long  VARCHAR2 (9) , 
     year              VARCHAR2 (4) , 
     quarter           VARCHAR2 (2) , 
     TBL_LAST_DT       DATE  NOT NULL 
    ) 
;

ALTER TABLE JS_DIM_DATE 
    ADD CONSTRAINT JS_DIM_DATE_PK PRIMARY KEY ( date_id ) ;

CREATE TABLE JS_DIM_PRODUCT 
    ( 
     product_id       INTEGER  NOT NULL , 
     product_code     VARCHAR2 (30)  NOT NULL , 
     product_name     VARCHAR2 (255)  NOT NULL , 
     subcategory_name VARCHAR2 (100)  NOT NULL , 
     category_name    VARCHAR2 (100)  NOT NULL , 
     TBL_LAST_DT      DATE  NOT NULL 
    ) 
;

ALTER TABLE JS_DIM_PRODUCT 
    ADD CONSTRAINT JS_DIM_PRODUCT_PK PRIMARY KEY ( product_id ) ;

CREATE TABLE JS_DIM_SHIP_ADDRESS 
    ( 
     address_id  INTEGER  NOT NULL , 
     region      VARCHAR2 (100)  NOT NULL , 
     country     VARCHAR2 (100)  NOT NULL , 
     state       VARCHAR2 (100)  NOT NULL , 
     city        VARCHAR2 (100)  NOT NULL , 
     postal_code VARCHAR2 (20) , 
     market      VARCHAR2 (100)  NOT NULL , 
     TBL_LAST_DT DATE  NOT NULL 
    ) 
;

ALTER TABLE JS_DIM_SHIP_ADDRESS 
    ADD CONSTRAINT JS_DIM_SHIP_ADDRESS_PK PRIMARY KEY ( address_id ) ;



DROP TABLE JS_FACT_ORDER_LINE;

CREATE TABLE JS_FACT_ORDER_LINE (
    fact_id      INTEGER PRIMARY KEY,
    order_code   VARCHAR2(40),
    order_priority VARCHAR2(10),
    ship_mode    VARCHAR2(50),

    -- REQUIRED FK
    order_date_id INTEGER NOT NULL REFERENCES JS_DIM_DATE(date_id),

    -- OPTIONAL FK
    ship_date_id  INTEGER REFERENCES JS_DIM_DATE(date_id),

    customer_id  INTEGER NOT NULL REFERENCES JS_DIM_CUSTOMER(customer_id),
    product_id   INTEGER NOT NULL REFERENCES JS_DIM_PRODUCT(product_id),
    address_id   INTEGER NOT NULL REFERENCES JS_DIM_SHIP_ADDRESS(address_id),

    quantity         INTEGER,
    discount         NUMBER(5,2),
    sales            NUMBER(12,2),
    profit           NUMBER(12,2),
    shipping_cost    NUMBER(12,2),
    returned_flag    VARCHAR2(1),
    tbl_last_dt      DATE
);





-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             5
-- CREATE INDEX                             0
-- ALTER TABLE                              9
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0

CREATE OR REPLACE DIRECTORY load_data_dir AS '/media/sf_STUDENT';
GRANT READ, WRITE ON DIRECTORY load_data_dir TO DWS;
